[build]
  publish = "mvp"

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200